### ISSUE TITLE
My sendmail is running on localhost port 25 on Ubuntu machine

### ISSUE THREAD

**Issue by victormarcus** [tachtler/jilter-InfoMilter#2]
When I try to use your application specifying port 25 and IP : 127.0.0.1  .
I am getting **java.net.SokcetException: Permission denied**  on line 
`this.serverSocketChannel.socket().bind(endpoint);`  of InfoMilter

**Comment by tachtler** [comment]
Hi kumbhaj,

port 25 is a high port and normally under Linux only the user "root" can run deamons that listen on port 25.

By the way, a Milter is normally not design to run on port 25, because it is NOT a MTA. 

Greetings
Klaus.

**Comment by kumbhaj** [comment]
Hi Klaus
Tell me where I am wrong. Isn't this application to read mails from Sendmail.
So you are saying this application is to be run on some other port like **9997** not on **25**.
How will it connect with Sendmail?

**Comment by tachtler** [comment]
Hi  kumbhaj,

sendmail is a very old MTA (Mail Transport Agent) - better to use Postfix. Personally I'm only work with Postfix. 

You have to tell the MTA (Postfix or Sendmail) to make a delivery to the Milter. Than the Milter does something. After that, the MTA (Postfix or Sendmail) get a result as a return code from the Milter like 250 OK or 550 REJECT.

That's how Milter works.

Maybe the following links can help you:
- http://www.sendmail.org/~gshapiro/8.10.Training/milterconfig.html
- http://www.elandsys.com/resources/sendmail/milter.html
- https://en.wikipedia.org/wiki/Milter
- https://metacpan.org/pod/Sendmail::Milter

Greetings
Klaus.

**Comment by victormarcus** [comment]
can milter send MIME to MTA?

**Comment by tachtler** [comment]
Hi  kumbhaj,

you have to know, that email is always and only text. Maybe encoded or encrypted, but always text. So if your encoding is right, the answer is yes.


Greetings
Klaus.

**Comment by victormarcus** [comment]
Thanks Klaus
