### ISSUE TITLE
Socket configuration for milter java

### ISSUE THREAD

**Issue by victormarcus** [tachtler/jilter-InfoMilter#3]
Hi,

Let's say my milter will run on 127.0.0.1  9997. I need to configure my Sendmail for this. Now, using this link: http://www.elandsys.com/resources/sendmail/milter.html 
I added this:  INPUT_MAIL_FILTER(`scam-back', `S=inet@8900@localhost, F=T, T=S:240s;R:240s;E:5m')dnl

I started infomilter with 127.0.0.1 9997

After restarting sendmail I get: "Local socket name inet@9997@localhost missing"

**Comment by kumbhaj** [comment]
Here is my skype Id: https://join.skype.com/invite/hnTlVMqVXQKo

**Comment by tachtler** [comment]
Hi Abhishek,

I'm not familiar with sendmail, because I only use Postfix, BUT can you try following command to check, if the MILTER (FooterMilter) is still running and you can connect to them:
```
telnet 127.0.0.1 9997
```
_Maybe you have to restart the service to stop the telnet connection_

Do you have
```
INPUT_MAIL_FILTER(`name', `S=inet@9997@localhost, F=T, T=S:240s;R:240s;E:5m')dnl
```
configured?

Greetings
Klaus.

**Comment by victormarcus** [comment]
Hi Klaus,

> INPUT_MAIL_FILTER(`name', `S=inet6:9997@localhost, F=T, T=S:240s;R:240s;E:5m')dnl

worked for me.

Does this application logs bcc recipients also? I couldn't find the bcc recipient in the data. My mail had one.

Greetings
Kumbhaj

**Comment by tachtler** [comment]
Hi Kumbhaj,

is your sendmail with FooterMilter now still running?

I'm sorry, but I do not understand you last question?

The logging possibilities described inside the footermilter.ini config file:
```
# Enable or disable TCP-Logging by setting the following parameter:
# true|false|yes|no|y|n (case insensitive)
#
# !IMPORTANT: Please set to false, true enables ONLY TCP-Logging see:
#             https://github.com/nightcode/jmilter
#  
#             If you want do DEBUG the FooterMilter.jar itself, please use the
#             parameter --> -d <-- as startup parameter as well!  
#
logging = false

# Set TCP-Logging Log-Level to INFO, WARN, ERROR, TRACE or DEBUG.
# Only relevant if logging = true
#
# !IMPORTANT: Please set to INFO to see the TCP-Logging, DEBUG will produce  
#             NO output. This is only for TCP-Logging see: 
#             https://github.com/nightcode/jmilter
#
loglevel = INFO
```
That's what are possible.

Greetings
Klaus.

**Comment by victormarcus** [comment]
Hi,

I am getting every information of the email headers but not BCC ?

**Comment by tachtler** [comment]
Hi kumbhaj,

only the sender can see the BCC: information, for the recipient the BCC: is always a normal TO:

Greetings
Klaus.

**Comment by victormarcus** [comment]
So there is not way to get BCC field data

**Comment by tachtler** [comment]
Hi kumbhaj,

not, if you are the recipient, because BCC (Blind carbon copy) prevent, that the the regular TO: recipient knows, that the E-Mail was sent to another e-Mail-address. The BCC: recipient get the e-Mail as TO:, because a E-Mail without TO: is not possible.

Greetings
Klaus.

**Comment by victormarcus** [comment]
Okay, thanks for your response, Klaus.

Regards,
Kumbhaj
