### ISSUE TITLE
Ability to handle mails simultaneously

### ISSUE THREAD

**Issue by victormarcus** [tachtler/jilter-InfoMilter#5]
I tried sending mails simultaneously. It fails sometimes

**Comment by tachtler** [comment]
Hi Abhishek,

I think this is not a MILTER problem, this is a MTA /Sendmail/Postfix problem. How many processes could sendmail start to send e-Mails to the MILTER?

Greetings
Klaus.

**Comment by victormarcus** [comment]
How can i fix this

**Comment by tachtler** [comment]
Hi Abhishek,

I'm not a sendmail expert. I can only give you a link to the Postfix documentation:
[http://www.postfix.org/MILTER_README.html](http://www.postfix.org/MILTER_README.html)

Inside the master.cf in Postfix, there is a column with maxproc.

See also another project of me, below is the link to my DokuWiki (sorry only in German language available, **BUT** you can see the `master.cf`)
[https://dokuwiki.tachtler.net/doku.php?id=tachtler:postfix_centos_7_-_footermilter_einsetzen_footermilter#etc_postfix_mastercf](https://dokuwiki.tachtler.net/doku.php?id=tachtler:postfix_centos_7_-_footermilter_einsetzen_footermilter#etc_postfix_mastercf)

Greetings
Klaus.

**Comment by victormarcus** [comment]
I tried 3 emails simultaneously, two milter were captured third wasn't. Sometimes this application reports EOF and no data arrives. Can sendmail not even transfer 3 mails to milter ? The  maxproc in postfix I guess is number of connections right ?

**Comment by tachtler** [comment]
Hi Abhishek,

yes, the maxproc is the number of connections. So every connection while the e-Mail was inside the delivery process, the MILTER react to a definition of it, CONNECT, HELO and so on.

Sorry, I think you have to figure out the problem by your own, and by your specific setup.

Greetings
Klaus.

**Comment by victormarcus** [comment]
Thanks
